# Custom search engines
c.url.searchengines = {
    'DEFAULT': 'https://duckduckgo.com/?q={}',
    'g': 'https://www.google.com/search?q={}',
    'q': 'https://www.qwant.com/?q={}',
    'ddg': 'https://duckduckgo.com/?q={}',
    'b': 'https://search.brave.com/search?q={}',
    'wes': 'https://es.wikipedia.org/wiki/{}',
    'wen': 'https://en.wikipedia.org/wiki/{}',
    'gh': 'https://github.com/search?q={}',
    'so': 'https://stackoverflow.com/search?q={}',
    'yt': 'https://www.youtube.com/results?search_query={}',
    'rd': 'https://www.reddit.com/search/?q={}',
    'arch': 'https://wiki.archlinux.org/?search={}',
    'aur': 'https://aur.archlinux.org/packages/?O=0&K={}',
    'npm': 'https://www.npmjs.com/search?q={}',
    'rae': 'https://dle.rae.es/{}',
    'ox': 'https://www.oxfordlearnersdictionaries.com/definition/english/{}',
    't': 'https://deepl.com/en/translator#en/es/{}',
}
